### ISSUE TITLE
Wrong parsing for empty categories iterable

### ISSUE THREAD

**Issue by normanjaeckel** [jazzband/django-ical#25]
If I create a ICalFeed without defining `item_categories`, the default value for this is not None but an empty tuple. See https://github.com/django/django/blob/master/django/utils/feedgenerator.py#L76.

But django_ical feedgenerator does not care about this, see https://github.com/jazzband/django-ical/blob/master/django_ical/feedgenerator.py#L109.

Result: I get `CATEGORIES:()` in my output which is seen as an event with one category named `()` by the client (at least thunderbird tries to show a category flag).

So we may check not only for None but also for empty tuple.

**Comment by cleder** [comment]
This is not a problem of django ical but rather of icalendar, fixed in:
https://github.com/collective/icalendar/pull/265
