### ISSUE TITLE
Attendee Responses

### ISSUE THREAD

**Issue by webaholik** [jazzband/django-ical#30]
I'm not seeing it in the documentation - what would be required to include attendees and rsvp responses for each event? Before diving too deep, can anyone on the team provide any direction or recommendations?

**Comment by aleksihakli** [comment]
At the moment the this package only offers read API for calendar events without response APIs. 

The current functionality relies on the Django syndication framework that is used to offer RSS feeds, so the code and functionality you'd need to implement would be quite different than the current code base offers, but it should be feasible if done correctly.

If you want to offer response functionality, you could implement a custom view and models that store the response information, and then specialize the code in this package to offer that information as wanted. If you are interested in researching the topic and implementing support in this package I think it's a good place for a PR.

Ideally there would just need to be a model for storing the response information and a view for receiving it.

I would recommend reading the [iCalendar RFC 2445](https://www.ietf.org/rfc/rfc2445.txt) before starting any implementation work.

**Comment by webaholik** [comment]
Note: I believe [RFC 5545](https://www.ietf.org/rfc/rfc5545.txt) replaces [iCalendar RFC 2445](https://www.ietf.org/rfc/rfc2445.txt)

**Comment by webaholik** [comment]
I have the update to enable output of attendees in the feed and have validated the feed via icalendar.org's icalendar validator. 

I hit a couple of snags along the way, both of which I believe are related to how calendar client apps handle calendar "subscriptions" via URL. I haven't been able to find anything specifically discussing these points, however, I did see mention that subscribed calendars cannot be edited.

1. Attendees w/ responses display perfectly in Apple Calendar, but not Google Calendar or Outlook. I believe the ability to see attendees on subscribed calendars has been suppressed in Google Calendar and Outlook.
2. The ability to respond to the event does not appear. My workaround is to include response links in the description text.

**Comment by aleksihakli** [comment]
Great! Opening a PR would probably be the good way to proceed if you'd like to include the implementation in this package, and we could also take a look at those problems together.

**Comment by aleksihakli** [comment]
Released in 1.7.0.
