### ISSUE TITLE
TypeError: EventFeed() missing 1 required positional argument: 'ICalFeed'

### ISSUE THREAD

**Issue by ebdavison** [jazzband/django-ical#37]
Following instructions here: https://django-ics.readthedocs.io/en/latest/usage.html
django 2.2

```
  File "/home/otcomm/otcomm/otcommproj/dallas/urls.py", line 15, in <module>
    url(r'^latest/feed.ics$', views.EventFeed(), name='event_feed'),
TypeError: EventFeed() missing 1 required positional argument: 'ICalFeed'
```

**Comment by aleksihakli** [comment]
Hey @ebdavison! Could you post your view code? [Here's a working example of the iCal feed usage](https://github.com/modeemi/website/blob/master/modeemintternet/feeds.py) from an active project that is deployed to [here](https://www.modeemi.fi) and offers the [feed here](https://www.modeemi.fi/feed/uutiset.ics).

**Comment by ebdavison** [comment]
Sure, this was right from the documentation/sample:

```
def EventFeed(ICalFeed):
    """
    A simple event calendar
    """
    product_id = '-//otcommittee.com//Calendar//EN'
    timezone = 'UTC'
    file_name = 'event.ics'

    def items(self):
        return Meeting.objects.all().order_by('-meeting_time')

    def item_title(self, item):
        return item.meeting_time

    def item_description(self, item):
        return item.meeting_time

    def item_start_datetime(self, item):
        return item.meeting_time
```

**Comment by aleksihakli** [comment]
@ebdavison you have defined a function called `EventFeed` with `def EventFeed(...)`. Use `class EventFeed(...)` instead to declare a class :)

**Comment by ebdavison** [comment]
oh ... well that certainly makes a difference.  But now a different error.  I do not see either `item_link` or `get_absolute_url` in your example mentioned above.  I am going to see what I can find on this ...

```
  File "/home/otcomm/otcomm/otcommenv/lib/python3.6/site-packages/django/contrib/syndication/views.py", line 62, in item_link
    'item_link() method in your Feed class.' % item.__class__.__name__
django.core.exceptions.ImproperlyConfigured: Give your Meeting class a get_absolute_url() method, or define an item_link() method in your Feed class.
```

**Comment by aleksihakli** [comment]
The error code is pretty self evident. You can find the documentation for setting the feed properties up in the Django syndication framework and feeds documentation. Good luck!
