### ISSUE TITLE
Add support for alarm

### ISSUE THREAD

**Issue by gabn88** [jazzband/django-ical#4]
Is this module still under development?

Or is it wiser to start from python icalendar?

**Comment by Pinkerton** [comment]
Hi! So sorry for the late response - must have missed the notification! I just started maintaining this module after the original author became too busy.

Are you referring to [this](https://tools.ietf.org/html/rfc5545#section-3.6.6) part of the icalendar RFC? This project is pretty handy for making icalendar work well with Django specifically, but the icalendar module probably supports that feature already if you're looking for something quick. I'd definitely love to see this module support everything that icalendar does!

PRs are welcome 😃

**Comment by gabn88** [comment]
I will come back to this. I use it now and it works fine! But I need alarm, so I will try to create a patch if I have time :)

**Comment by cleder** [comment]
After 2 years of inactivity this is a wontfix
