### ISSUE TITLE
[TypeError: main() missing required positional argument request ]

### ISSUE THREAD

**Issue by Saad-py** [jazzband/django-ical#42]
I am getting this error while following a youtube Django tutorial and I know that this is not the plate for Django issues so I went to Django git-hub but there I can't open an issue so I came here for help. The error says that I am missing an argument for the main function that returns the HttpResponse in that I have included request but it says that I haven't. This error occurred while I was making the migrations for my project. Al I want is to get the link to view the server or web and fix this. Kindly help me, it will benefit me.. I am following Tech with Tim's youtube course for Django and React Js I also asked him thrice but there was no reply.

**Comment by aleksihakli** [comment]
Could you please post the full error stack trace and the code you are using?

**Comment by aleksihakli** [comment]
Closing the issue since there has been no reply in two weeks. Hope you found a solution :)
