### ISSUE TITLE
Content Type should contain `;`instead of `,`

### ISSUE THREAD

**Issue by PabloLeCrapaud** [jazzband/django-ical#48]
In pull request responding to the #33, you added:
        response = HttpResponse(content_type='text/calendar, text/x-vcalendar, application/hbs-vcs')

The correct syntax should be:
        response = HttpResponse(content_type='text/calendar; text/x-vcalendar; application/hbs-vcs')

In the current situation, it does not work everywhere...

**Comment by aleksihakli** [comment]
Hi @PabloLeCrapaud! Would you be interested in opening a PR including the fix for the content type?

**Comment by PabloLeCrapaud** [comment]
Of course! But I have to confess I'm not sure that my proposal was correct... In my case I had to replace it by content_type='text/calendar' only, so I'm not sure the problem was the `;`. I'll check and open a PR if needed...

**Comment by aleksihakli** [comment]
Content-Type header does not seem to allow multiple values in the response, although a client can define multiple accepted media types. The server could return a suitable response with requested Content-Type if it can.

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept (request)
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type (response)

Should we just define the Content-Type as it was previously defined as `feedgen.mime_type`?

**Comment by PabloLeCrapaud** [comment]
Thanks a lot! It works fine!
