### ISSUE TITLE
Wrong Content-Type charset declaration

### ISSUE THREAD

**Issue by lchanouha** [jazzband/django-ical#57]
Hello
`mime_type = "text/calendar; charset=utf8"`
should be replaced by:
`mime_type = "text/calendar; charset=utf-8"`

References: 
- Google's ics implementation returns: content-type: text/calendar; charset=utf-8
 - https://www.w3.org/International/articles/http-charset/index

Regards,

**Comment by aleksihakli** [comment]
Good catch :) Would you like to open a PR for updating this behaviour @lchanouha?

**Comment by lchanouha** [comment]
Done #58

**Comment by aleksihakli** [comment]
PR upstreamed and fix available in release version 1.8.4.
