### ISSUE TITLE
CATEGORIES shows up in feed twice.

### ISSUE THREAD

**Issue by mjfinney** [jazzband/django-ical#63]
Since updating to the latest version, CATEGORIES shows up in my feed twice.
It is listed twice in ITEM_ELEMENT_FIELD_MAP on line 63 and line 77 which might be the cause of the problem.

https://github.com/jazzband/django-ical/blob/0c32c51c7336946fe87b477873904391bf1fb74c/django_ical/feedgenerator.py#L63

**Comment by aleksihakli** [comment]
Thanks for reporting! Yeah there seem to be two entries for categories. Would you happen to have the change of making a PR for fixing this?
